version: "3.2"

volumes:
  redis:
    external: true

services:
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
        - 6379:6379
    volumes:
        - $PWD/redis-data:/var/lib/redis
        - $PWD/bin/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
        - REDIS_REPLICATION_MODE=master

    networks:
      node_net:
        ipv4_address: 172.28.1.4

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 127.0.0.1:8020:8020
    depends_on:
        - redis
    links:
        - redis


networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
