version: "3.2"

volumes:
  redis:
    external: true

services:
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
        - 6379:6379
    volumes:
        - $PWD/redis-data:/var/lib/redis
        - $PWD/bin/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
        - REDIS_REPLICATION_MODE=master
        - TZ=Europe/Moscow

  app:
    build:
      context: .
      dockerfile: appDockerfile
    ports:
        - 5000:5000
    env_file:
        - ./.env
    depends_on:
        - redis
    links:
        - redis

  worker:
    build:
      context: .
      dockerfile: workerDockerfile
    env_file:
        - ./.env
    depends_on:
        - redis
        - app
    links:
        - redis
